### ISSUE TITLE
Update to support http and the knative world

### ISSUE THREAD

**Issue by matthewmcnew** [projectriff/python3-function-invoker#9]
Hi Folks,

For fun, I started updating this to support 'http' invocations for the knative world. https://github.com/matthewmcnew/python3-function-invoker. With a planned PR eventually. 

Would love any thoughts/advice or other work in progress if it exists.

**Comment by dturanski** [comment]
@matthewmcnew . Thanks for your interest.  Please see https://github.com/projectriff/riff/blob/master/CONTRIBUTING.adoc  and sign the contributors agreement if you haven't already.  Meanwhile I'll take a look at your changes.

**Comment by fbiville** [comment]
Now merged, thanks!
